### ISSUE TITLE
Can only change difficulty faces to one specific sprite.

### ISSUE THREAD

**Issue by Sushi8756** [Alphalaneous/HappyTextures#10]
More of a suggestion of a issue but on screens like LevelInfoLayer, LevelSelectLayer, and also GJDifficultySprites in general, I try to change the sprite of the difficulty icon and want it to be based off the difficulty of the level (Easy would be sprite1.png and Normal would be sprite2.png, etc.). I cant and only can change it to one sprite, no matter what difficulty it is.

**Comment by Alphalaneous** [comment]
Why don’t ya change the difficulty face in just a normal texture pack then?

**Comment by Sushi8756** [comment]
> Why don’t ya change the difficulty face in just a normal texture pack then?

Yeah I can but I want it to have one texture in certain areas, and use a different texture for the same difficulty face in other areas.

**Comment by Alphalaneous** [comment]
There currently isn't any form of conditional modifying, unsure if I will add it, it may fit better if someone were to make a UI scripting framework
