### ISSUE TITLE
chest-opened-overlay also changes secret chests' color making them look weird

### ISSUE THREAD

**Issue by M336G** [Alphalaneous/HappyTextures#14]
![image](https://github.com/user-attachments/assets/260dd6b8-30dc-48cb-a53d-68a5465d8b09)

Already opened all my chests so I can't really show more unfortunately

Suggestion: Adding new fields for each chest color

**Comment by Alphalaneous** [comment]
Ooh this is gonna be fun to test, will look into, thanks for reporting

**Comment by Alphalaneous** [comment]
Fixed
