### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by JordanTRS** [Alphalaneous/HappyTextures#16]
I'll be honest I have no clue what's causing this crash, hopefully the crash handler and error message can help..?

![image](https://github.com/user-attachments/assets/438093af-b7a6-4b40-9a3e-4700dd90218d)

**Comment by JordanTRS** [comment]
from what I can tell I think it has something to do with using the "disable-pages": true line, but i dont know much else

**Comment by Alphalaneous** [comment]
Are you removing any nodes manually? Can you send the log as a file?

**Comment by JordanTRS** [comment]
No I wasn’t removing nodes, the weird thing is that I undid my changes, opened the game and it ran fine, then I re-added the exact same code and suddenly it was having no issues. I sadly don’t have the old code anymore but it is working now, although I don’t know how I fixed it really

**Comment by Alphalaneous** [comment]
This is related to the crash you recently posted (same stack trace)
