### ISSUE TITLE
How can i add background on tp workshop? 

### ISSUE THREAD

**Issue by JohnnyEnglish83** [Alphalaneous/HappyTextures#18]
I tried to add background on colors.json but its not working
![Screenshot_20240916-215006](https://github.com/user-attachments/assets/4b45b576-f225-4eeb-92b7-4bb73ace510e)

**Comment by JohnnyEnglish83** [comment]
![Screenshot_20240916-214755](https://github.com/user-attachments/assets/f01d140c-8b90-4a3d-a110-27571f595241)

**Comment by Alphalaneous** [comment]
Texture workshop has its own colors and modes, colors.json is just for vanilla hardcoded colors. If you wish to modify their layer, name a file as the same ID as the layer (check devtools) and then grab the nodes following the docs and change them there.
