### ISSUE TITLE
Geode update notification crashes...?

### ISSUE THREAD

**Issue by JordanTRS** [Alphalaneous/HappyTextures#19]
As far as I can tell whenever Geode does the "New Update Available" notification, if you have a HT Texture Pack loaded it'll crash your game. 
![image](https://github.com/user-attachments/assets/94ff5992-3fc3-4548-aace-de11cba85b68)
If I remove the TP, update Geode, then reload the TP, it works perfectly fine. This also happened the last time Geode had an update, so it's consistent.

**Comment by Alphalaneous** [comment]
Oh this is a funny one, turns out geode doesn’t have a nullptr check on their own button and this crash can even happen in vanilla with the no geode UI flag enabled. Though it happening here shows an underlying issue that the page disabling itself isn’t properly being handled which I will look into

**Comment by Alphalaneous** [comment]
After repeatedly testing, I cannot replicate this crash at all.

**Comment by Alphalaneous** [comment]
Can you send the updated version of the pack

**Comment by JordanTRS** [comment]
https://drive.google.com/drive/folders/1xTemR5QLoEfDxdd4AQejeSEGASGWulAo?usp=drive_link
let me know when you have it downloaded so i can remove this link (i dont want this pack to be public currently)

**Comment by Alphalaneous** [comment]
Can confirm this is a geode bug and will be fixed on their end

**Comment by JordanTRS** [comment]
alright, thank you!

**Comment by Alphalaneous** [comment]
Can confirm it is a sinister third thing

**Comment by Alphalaneous** [comment]
Sinister as in I am somehow causing the original menus to sometimes not exist even tho I never remove/destroy them, but only sometimes does this happen.

**Comment by JordanTRS** [comment]
Might it be an issue with another Geode mod I have installed?

**Comment by Alphalaneous** [comment]
Can you check if the new pages api update resolves it?

**Comment by JordanTRS** [comment]
what exactly am I checking for? Am I checking to make sure the game doesn't crash? because that might have to wait a day or two since it only would happen for me the first time i open the game with a HT texture pack loaded

**Comment by JordanTRS** [comment]
so far I can confirm that closing the game and reopening did not crash the game

**Comment by Alphalaneous** [comment]
Ye, just come back if something weird does happen. It's a very hard bug to debug lol

**Comment by JordanTRS** [comment]
I noticed before that the Geode error message also caused this bug to occur (it happens for me cause i have a few mods saved that are outdated), and today the game didn't crash when the error message appeared, so as far as I can tell your fix worked

**Comment by JordanTRS** [comment]
I've got some bad news
![image](https://github.com/user-attachments/assets/9a591ac8-ae70-4156-ae47-79e68c58225c)

**Comment by JordanTRS** [comment]
![image](https://github.com/user-attachments/assets/19347cbf-c15f-406f-8d5c-881973b43c73)
happened again

**Comment by Alphalaneous** [comment]
Fixed in 1.6.5
