### ISSUE TITLE
Disabling Pages is broken

### ISSUE THREAD

**Issue by JordanTRS** [Alphalaneous/HappyTextures#20]
Placing your mouse over pages that have been disabled will consistently crash your game.
![image](https://github.com/user-attachments/assets/ae2afd49-fb59-46ff-aec4-4a27557d3133)
There's nothing else to say here

There's also an issue where trying to disable the pages for the online options page doesn't update the buttons until you place your mouse on the pages node in DevTools, only then will it update, and it WON'T crash. The crashing only seems to occur if the pages update automatically, which the buttons on the online section don't seem to do.
![image](https://github.com/user-attachments/assets/19c0df10-f260-40e3-98da-80f2c6061e2b)
![image](https://github.com/user-attachments/assets/b5710b45-3794-4341-9353-f731bcd9dffb)
None of your custom attributes will take affect either, making the online buttons completely impossible to edit as far as I can tell.

**Comment by Alphalaneous** [comment]
Fixed in the latest commit, doing some evil shenanigans to make this work properly
