### ISSUE TITLE
Suggestion: Change color for music library's cells

### ISSUE THREAD

**Issue by M336G** [Alphalaneous/HappyTextures#22]
`MusicBrowser`
![14898406608215212032_20241006135328_1](https://github.com/user-attachments/assets/d14395e4-8ad3-46a0-bec3-2df84438da75)

_I've already reported those on Discord, but figured it'd be better to post them here to track them more easily._

**Comment by Alphalaneous** [comment]
Completely forgor about this one. Will try when I have the chance :3

**Comment by Alphalaneous** [comment]
Done!
