### ISSUE TITLE
[Suggestion] Placeholders for Text elements

### ISSUE THREAD

**Issue by fibberclip** [Alphalaneous/HappyTextures#24]
It would be sick as hell if modifying text elements allowed you to use Placeholders to display different info, sort of how it's handled in Minecraft's FancyMenu mod, for example:

- {gameVersion} would display "2.2"
- {player} would display the player's Username
- {loaderVersion} would display Geode's version
- {timeHour} would display the local time's current hour

This could potentially be also expanded to per-level placeholders to show in level info menus or pause menus, such as Level Creator, Best Percentage, Attempts, etc!

**Comment by Alphalaneous** [comment]
Done!

**Comment by DeepRsnanceX** [comment]
hey, im curious abt something and i thought i'd just ask here - is it possible to add new fonts apart from the vanilla ones and use them in text elements? and if so, is there anything special i need to do for the mod to detect them?

**Comment by Alphalaneous** [comment]
You can indeed add new fonts, you would specify the fnt file in the json similar to how you do for vanilla fonts. They'd be placed in the same area as if you were replacing the vanilla ones too, nothing special needed but do be sure you have the required quality levels

**Comment by DeepRsnanceX** [comment]
Oooo aight i see, tysm!! :D

**Comment by DeepRsnanceX** [comment]
Another question lol sorry but i'm starting to make bigger things fr now; is it possible to add some sort of delay time in-between a sequence of actions? for example i want 2 moveTo actions to move an element in and then out of a layer, but i ofc want a delay time in-between the enter and exit actions, is that possible?
