### ISSUE TITLE
Colored Text in custom Pop-ups/Alerts

### ISSUE THREAD

**Issue by fibberclip** [Alphalaneous/HappyTextures#25]
I don't know if this is already possible, but a way to color certain words in custom made Alerts would be pretty sick, maybe have it either via something like "<red>Red Text</red>" or something like Minecraft's "&4Red Text"/"§4Red Text" format for colored words

**Comment by Alphalaneous** [comment]
This is indeed already possible, gd’s got a similar color code system 
<cr>Red text</c> for example. You can find a list of these here: https://wyliemaster.github.io/gddocs/#/topics/tags

**Comment by fibberclip** [comment]
OOH i wasn't aware of this, sorry and thank u!!
