### ISSUE TITLE
[Suggestion] CCMenuItem support

### ISSUE THREAD

**Issue by itzRocked** [Alphalaneous/HappyTextures#27]
i think it would be pretty cool to have shortcut button for example: button to create tab :)

**Comment by Alphalaneous** [comment]
I do not know what you mean

**Comment by itzRocked** [comment]
so i was trying to make some kind of shortcut button
![image_2024-11-22_230758254](https://github.com/user-attachments/assets/a6d1c1f3-7395-49e9-9dd5-03eaab0a01f9)
and i was wondering how can i open the Create menu on the button i made, so i looked in the DevTools and this shows up in one of the buttons in MenuLayer
![image](https://github.com/user-attachments/assets/117baea7-f7be-461c-b3f8-f6006c1b76f2)

**Comment by Alphalaneous** [comment]
Unfortunately that is not an easy feat and is outside of the scope of this mod.

**Comment by Alphalaneous** [comment]
I've got good news

**Comment by Alphalaneous** [comment]
Aaand doned!

**Comment by itzRocked** [comment]
yooo, w update (sorry im kinda late to the party lmao)
