### ISSUE TITLE
[Suggestion] Texture Randomization

### ISSUE THREAD

**Issue by DeepRsnanceX** [Alphalaneous/HappyTextures#28]
Add a way for Texture Packs (preferably via UI modifications) to allow randomization of certain selected textures.

For example, let's say i wanna make a pack that chooses a random play button on the main menu. I'll store all possible play buttons inside the "play" folder in my pack, and then my UI modification for MenuLayer would need to contain something like this:

```
"play-button": {
    "attributes": {
        "randomize-sprite": true,
        "sprite": "play/*",
        "random-mode": "load"
    }
}
```

This would then enable texture randomization for the selected element, and would take everything inside the "play" folder as a possible texture.
Random mode could be set to 2 options:
- "load": Randomizes the texture everytime the element is loaded (In this case, going to any other menu and then BACK to the main menu would show a different texture each time)
- "session": Randomizes the texture only once per game session

Not exactly sure how possible this is, or how would it even work with some sprites like the "Level Complete!" one at the end of a level or the "New Best!" one on death. Might be a little too insane, but would be cool

**Comment by Alphalaneous** [comment]
Doned!
