### ISSUE TITLE
Crashes on startup (Android64)

### ISSUE THREAD

**Issue by Kingminer7** [Alphalaneous/HappyTextures#3]
I updated to 1.1.6 and the game crashes right after the menu music starts.
[temp_232300371444455.dmp.txt](https://github.com/Alphalaneous/HappyTextures/files/15403663/temp_232300371444455.dmp.txt)

**Comment by Alphalaneous** [comment]
Does this crash still occur if you disable main levels editor?

**Comment by Alphalaneous** [comment]
And if so, send new log

**Comment by Alphalaneous** [comment]
Try 1.1.7
