### ISSUE TITLE
Not all callbacks work

### ISSUE THREAD

**Issue by Boomyboomer123** [Alphalaneous/HappyTextures#30]
I made a button and I set it's callback attribute to onMySavedLevels on activation and it worked fine but when I changed it to onPlay (I changed the class too) it wasn't doing anything after I pressed it. Here is my code: (it broke a bit when I uploaded it to Google drive to get it on my phone)
[MenuLayer.json](https://github.com/user-attachments/files/18167735/MenuLayer.json)

**Comment by Alphalaneous** [comment]
That json shows MenuLayer::onCreator. Have you tried reloading your packs when setting onPlay?

**Comment by Alphalaneous** [comment]
Should be resolved now, please create a new issue if this occurs with another callback, it all seems to work fine from my testing but evil shenanigans are among us
