### ISSUE TITLE
action attributes happen instantly

### ISSUE THREAD

**Issue by Boomyboomer123** [Alphalaneous/HappyTextures#31]
It's not rly an issue but I made a pack [menu animations.zip](https://github.com/user-attachments/files/18269287/menu.animations.zip) and it works fine when the fast menu option is on but when it's off then it kinda looks bad. Could you make it so action attributes happen after the transition ends pls? (the normal attributes still should happen instantly ofc)

**Comment by Alphalaneous** [comment]
I cannot do it the way you want as that would over complicate things, especially when there are use cases where you would want an action to run instantly. Instead, I added a new object called "after-transition" which lets you run your changes after the transition has finished. See the updated wiki for more details.
