### ISSUE TITLE
Does not override font for Counter Labels

### ISSUE THREAD

**Issue by Garygoh884** [Alphalaneous/HappyTextures#5]
As this mod replaces custom Pusab fonts with its original in levels, it does not override the font used for Label Counters. This happens while playing and editing the level.

In this case, I used Texture Loader and HappyTextures mod as shown.

![Screenshot 2024-05-27 120917](https://github.com/Alphalaneous/HappyTextures/assets/13744216/a1369005-1aa3-4a32-b652-27f68be871dc)

**Comment by Alphalaneous** [comment]
Fixed in v1.3.3
