### ISSUE TITLE
Missing texture play button when "Allow UI Modifications" is enabled

### ISSUE THREAD

**Issue by Aqua0A** [Alphalaneous/HappyTextures#6]
i don't know if it's an overlap with mods but the play button only disappears with the option ticked and idk how I could fix it

![image](https://github.com/Alphalaneous/HappyTextures/assets/165586852/fd54a41e-34ed-4cba-b2ed-bc2f7f3b2339)

**Comment by Alphalaneous** [comment]
One of your texture packs set the sprite of the play button to something that doesn't exist
