### ISSUE TITLE
Crash on launch when hot reload is enabled

### ISSUE THREAD

**Issue by Minemaker0430** [Alphalaneous/HappyTextures#7]
![image](https://github.com/Alphalaneous/HappyTextures/assets/85040155/f39c4dfe-7c0c-4885-824a-5ddfed622b20)

Trying to enable texture packs then leaving the menu with Happy Textures enabled freezes the game with no crashlog
Disabling Happy Textures, enabling texture packs, then reenabling Happy Textures freezes your game on startup

**Comment by Alphalaneous** [comment]
Does this happen with all texture packs? If not, can you send a zip of the pack that is yielding this freeze

**Comment by Alphalaneous** [comment]
I am unable to replicate with the packs they sent, if anyone can replicate this issue, please report it here

**Comment by Alphalaneous** [comment]
I'm leaving this open even though it is fixed for general users, as it still can be broken when you enable the toggle

**Comment by Alphalaneous** [comment]
Likely fixed in 1.7.1
