### ISSUE TITLE
Counter object ignores blending on first attempt

### ISSUE THREAD

**Issue by Ks4FnDnR301** [Alphalaneous/HappyTextures#8]
title. don't know if this issue affects solely the counter object. but i can confirm this is a happy textures issue.
i also tried turning off all of the five settings that the mod gives you. there was no change in behavior

https://github.com/user-attachments/assets/79c80d0f-d6fc-4bae-8385-96125a6555ec

**Comment by Alphalaneous** [comment]
Should be resolved now in 1.3.20
