### ISSUE TITLE
[suggestion] Cascading Icon Additions

### ISSUE THREAD

**Issue by Aktimoose** [Alphalaneous/HappyTextures#9]
It would be cool if there was potentially a way for multiple packs to add icons even if those packs use the same icon ids, like for example:
Pack 1: Adds Cube 485, 486, 487
Pack 2: Adds different Cube 485, 486, 487
Result: there is now Cube 485, 486, 487, 488, 489, 490
I'm not sure how feasible this is? This would also have to be used in conjunction with Custom Patcher, or another system, to even allow for more icons in the first place, but I think this would be great for icon texture packs.

**Comment by Alphalaneous** [comment]
I have this in the back of my plans. Also, custom patcher stuff is not cross platform in any way and very buggy, since it’s not scalable, I’d want to go for a fully hook based approach which isn’t the easiest

**Comment by fibberclip** [comment]
HUGE VOUCH need this so badly 🙏🙏🙏🙏🙏🙏

**Comment by Alphalaneous** [comment]
This is now in the scope of the More Icons mod by hiimjustin000
